name: CI with Postman Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt'

    # Build the application
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots verify
      
      #List target dir
    - name: List target directory
      run: ls -l target/
      
    # Start Spring Boot
    - name: Start Spring Boot
      run: java -Dspring.profiles.active=test -jar target/use-api-7.1.1-SNAPSHOT.jar &
      env:
        SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/testdb

    # Wait for Spring Boot to start
    - name: Wait for Spring Boot
      run: |
        for i in {1..10}; do
          curl --fail http://localhost:8080/actuator/health && break || sleep 10;
        done

    # Run Postman Tests with Newman
    - name: Run Postman tests
      run: |
        npm install -g newman
        newman run src/main/resources/postman_collection/use-webapi.postman_collection.json


    # Cleanup
    - name: Stop Spring Boot
      run: pkill -f 'java -Dspring.profiles.active=test'
